Add SOC project proposal
openhwgroup/core-v-docs pull request #199
Opened 2020-09-21 22:03 UTC by DBees

2020-09-22 07:26 UTC, davideschiavone requested changes

2020-09-22 07:26 UTC, davideschiavone commented on program/Preliminary project proposal for MCU SoC_Sep20.txt
> +-- energy efficiency)
extra parenthesis here ")" to be removed

2020-09-22 07:26 UTC, davideschiavone commented on program/Preliminary project proposal for MCU SoC_Sep20.txt
> +- Verification: intermediate level of quality, this is not a
this is not a "requirement" (last word missing)

2020-09-22 07:28 UTC, davideschiavone requested changes

2020-09-22 07:28 UTC, davideschiavone commented on program/Arnold II preliminary project proposal.md
> +-- energy efficiency)
same here , extra ")"

2020-09-22 07:28 UTC, davideschiavone commented on program/Arnold II preliminary project proposal.md
> +- FLL or PLL: does this come from ETHZ? All involved: Global Foundries, Cadence, ETHZ
Here we should also add the comments about it from yesterda, i.e. the idea of buying it externally from an IP vendor

2020-09-22 12:37 UTC, MikeOpenHWGroup commented on program/Preliminary project proposal for MCU SoC_Sep20.txt
> +- assumed ready now
The CV32E40P core RTL is **_not_** ready now.  We expect "RTL Freeze" for the core to be in October, 2020.  The current state of the RTL is such that it can be used for preliminary testing and synthesis.  You will want to wait for the official release before going much beyond that.

2020-09-22 12:40 UTC, MikeOpenHWGroup commented on program/Preliminary project proposal for MCU SoC_Sep20.txt
> +-- what about peripherals such as I^2C - do they need the same level of verification
Given that OpenHW has promoted itself as a provider of "industrial quality" IP, I think the answer here must be "yes, the peripherals must be the same level of quality".  It will be difficult for an end-user to distinguish between the CV32E40P core and the SoC.  If any peripheral of the SoC is low quality, it will reflect badly on the CV32E40P (and by extension, all of OpenHW).

2020-09-22 12:40 UTC, MikeOpenHWGroup reviewed
Added a few comments.

2020-09-22 12:51 UTC, davideschiavone commented on program/Preliminary project proposal for MCU SoC_Sep20.txt
> +- assumed ready now
Hi @MikeOpenHWGroup . Good that you pointed out, @DBees meant that for this project, the verification is given as done :) now means at the beginning of that project

2020-09-22 12:52 UTC, davideschiavone commented on program/Preliminary project proposal for MCU SoC_Sep20.txt
> +-- what about peripherals such as I^2C - do they need the same level of verification
Good point @MikeOpenHWGroup , this should be taken into account when we estimate the resources for the MCU project - thanks

2020-09-22 13:57 UTC, hpollittsmith commented on program/Arnold II preliminary project proposal.md
> +- Re-use of Pulpissimo architecture with certain modifications
"accelerator"

2020-09-22 13:57 UTC, hpollittsmith commented on program/Arnold II preliminary project proposal.md
> +- standard cells libraries and memory macros (Synopsis)
Synopsys

2020-09-22 13:57 UTC, hpollittsmith commented on program/Preliminary project proposal for MCU SoC_Sep20.txt
> +-- what about peripherals such as I^2C - do they need the same level of verification
Yes, definite implications for resources and timeline. I think some of the reasoning behind relaxing the verification requirement was that these blocks have seen silicon a number of times, and the purpose of the platform is to evaluate the CV32E40P/eFPGA rather than provide production volume SoC--but it is a good point that we don't want questions about overall quality.

2020-09-22 14:13 UTC, MikeOpenHWGroup commented
@hpollittsmith commented:
> these blocks have seen silicon a number of times

Understood.  Not to beat anyone on the head with this, but the RI5CY core has seen silicon a number of times and yet we've been very busy getting the RTL for CV32E40P cleaned up and fully verified.

2020-10-06 22:15 UTC, DBees commented
This is superseded by https://github.com/openhwgroup/core-v-docs/blob/master/program/Preliminary%20project%20proposal%20for%20MCU%20SoC.md

2020-10-06 22:15 UTC, closed without merging