:bug: correct cycle count for CSR accesses
openhwgroup/core-v-docs pull request #275
Opened 2020-11-23 11:34 UTC by davideschiavone

Fix for #274

2020-11-23 14:15 UTC, Silabs-ArjanB commented on cores/cv32e40p/user_manual/source/pipeline.rst
> +  |                       | 1 (all the other cs registers)       |                                                             |
CSR instead of cs

2020-11-23 14:16 UTC, Silabs-ArjanB requested changes
Hi Davide, looks good to me if you make the small change requested.

2020-11-24 13:09 UTC, davideschiavone commented
> 
> 
> Hi Davide, looks good to me if you make the small change requested.

Done

2020-11-24 13:53 UTC, Silabs-ArjanB approved these changes

2020-11-24 14:09 UTC, merged