Re-organisation of program directory into project folders
openhwgroup/core-v-docs pull request #366
Opened 2021-03-11 03:58 UTC by DBees

Signed-off-by: DBees <duncan@openhwgroup.org>

2021-03-12 20:09 UTC, MikeOpenHWGroup requested changes
Looks (mostly) good to me @DBees.  The new directory structure is an improvement.  About `Management of Projects Within OpenHW Group V3.docx`:
- its an empty file: is that your intent?
- since its under review control we could get rid of the "V3" post-fix in the filename.

2021-03-16 20:01 UTC, DBees commented
Hi Mike I'm not sure why it is "empty", my PR deleted it (I think). That file should be removed

2021-03-16 20:22 UTC, MikeOpenHWGroup commented
> Hi Mike I'm not sure why it is "empty", my PR deleted it (I think). That file should be removed

Strange.   That file is does not exist in your PR, so I'll go ahead a see what a merge does...

2021-03-16 20:23 UTC, MikeOpenHWGroup approved these changes

2021-03-16 20:23 UTC, merged