2021-04-09 CVA6 meeting minutes
openhwgroup/core-v-docs pull request #384
Opened 2021-04-09 15:50 UTC by MikeOpenHWGroup

Please let me know if I missed anything and/or made any errors.

2021-04-09 16:23 UTC, jquevremont requested changes
Action: **Pranay** to investigate PPA of commerical offerings of RV32GC.
==>
Action: **Pranay** to estimate PPA (actually areas and FP latency) of scenarios: RV32D, RV32F, emulation of DP on RV32I

2021-04-09 19:12 UTC, MikeOpenHWGroup commented
Thanks @jquevremont.  I'll wait until Monday morning my time (4/12 @ noon UTC) to see if there are additional comments.

2021-04-16 15:07 UTC, MikeOpenHWGroup commented
Added the presentation from today's meeting.

2021-04-19 08:13 UTC, zarubaf approved these changes

2021-04-19 12:26 UTC, merged