Create CV32E41P project proposal.md
openhwgroup/core-v-docs pull request #414
Opened 2021-06-18 15:43 UTC by tariqkurd-repo

2021-06-22 09:31 UTC, tariqkurd-repo commented
I've signed the legal agreement so this check should pass now.

2021-06-23 15:03 UTC, davideschiavone requested changes

2021-06-23 15:04 UTC, davideschiavone requested changes

2021-06-23 15:04 UTC, davideschiavone commented on program/Project Descriptions and Plans/CV32E41P/CV32E41P project proposal.md
> +Davide Schiavone
It cannot be me as the PM must be an OpenHW Group member

2021-06-23 15:05 UTC, closed without merging

2021-06-23 15:05 UTC, tariqkurd-repo commented
will resubmit as a new PR